name: Pipeline CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  validar-projeto:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Validar HTML
        run: npm run lint:html

      - name: Validar CSS
        run: npm run lint:css

      - name: Executar testes
        run: npm test